### ISSUE TITLE
sfawefd3d verification

### ISSUE THREAD

**Issue by khokhlov** [ahay/src#108] opened 2016-04-18 10:52 UTC
Dear sfawefd3d developers,
 
I like sfawefd3d simulation software. It is highly optimized and simple. However I am having troubles with setting it to work.
 
I am trying to benchmark the software against analytical solutions. It is OK in case of the free-space, provided that I multiply sfawefd3d output by c^2/h^3, where c is the sound of speed, h is the grid step size.
 
But when it comes to the double half space model (air+Earth), amplitudes do not fit to the analytical solution (please, see my pictures attached). There is a factor, which I cannot figure out .. I have tried to shift the source position by 0.5 or 1.0 of the grid step in x,y,z directions, but with no success.
 
Could you, please, suggest what I could do?
 
Scrips and input files: https://github.com/khokhlov/sfawefd3d_test
 
Thank you very much !
 
With best regards,
Nikolay

**Comment by khokhlov** [comment] 2016-04-22 12:50
Here is IPython notebook for this example: https://github.com/khokhlov/sfawefd3d_test/blob/master/sfawefd3d_test.ipynb

**Comment by huidotwang** [comment] 2016-05-12 07:36
Hi Nikolay,

I committed one patch to resolve the issue you were referring to. Now solutions for both homogeneous and fluid half-space cases match the Green's functions. However the Ricker wavelet you were using for the sfawefd3d code should be modified before passing the program. Yet, that is not a bug of the codes, but just notation consistence with the ones you used for Green's function.
You can get more details from he iPython notebook **sfawefd3d_issue_explained.ipynb**, which I put in the forked repository from yours.
[https://github.com/huidotwang/sfawefd3d_test](url)
I think the issue has been resolved and we could close it if you agree.

**Closed** 2016-05-12 20:48 UTC
