### ISSUE TITLE
Mistake Download Sigsbee model

### ISSUE THREAD

**Issue by ale00999-lab** [ahay/src#259] opened 2022-01-07 23:02 UTC
Hello everyone!

I have been trying to download the Sigsbee2B  Model for my degree  master project, but I have the following error in the attachment.
Any help to get this model would be very helpful.

**Additional context**

![Madagascar_Import_Segy](https://user-images.githubusercontent.com/65864942/148617713-b9eda77a-4cae-47e1-92b8-871c81ed54a3.png)

**Comment by sfomel** [comment] 2022-01-10 16:56
You can update your copy of Madagascar to the latest development version or download the data directly from https://www.reproducibility.org/data/sigsbee/

The new stable version (madagascar-4.0) will be released soon.

**Comment by deckerla** [comment] 2022-01-11 17:06
@ale00999-lab I believe your difficulties are from trying to open `.rsf` or `.sgy` files as text or word documents, which may be chosen as the default on your machine.

A good way to access the data is by installing Madagascar and then running the script shown here:
https://github.com/ahay/src/blob/master/book/data/sigsbee/model2A/SConstruct
A rendering of this example is available in the reproducible documents section here:
https://reproducibility.org/RSF/book/data/sigsbee/paper_html/node3.html

Running the script may be done using SConstruct by navigating to the directory `$RSFSRC/src/blob/master/book/data/sigsbee/model2A/` and running `sons`

It looks like you are running a Windows machine.  If you have access to a Unix based system, like Linux or Mac, installing Madagascar is significantly easier.  If not, instructions for Windows may be found here:
https://www.reproducibility.org/wiki/Windows

Be aware that you will have to install Cygwin, which is a non-trivial process.  Cygwin provides a Unix like environment in Windows.

**Comment by ale00999-lab** [comment] 2022-01-12 19:55
@deckerla 
Thanks for your detailed explanation.
I have Ubuntu 20 and use the following path
$ RSFSRC / src / blob / master / book / data / sigsbee / model2A /
and scons

I am getting the error from the attachment, it seems to me that it is a problem with the server.

![error_download_filr](https://user-images.githubusercontent.com/65864942/149210630-b1be97ed-4a16-4ca3-92dd-a5bc610208dd.png)
![SConstruct](https://user-images.githubusercontent.com/65864942/149210647-f3363d02-25ae-4d6b-adac-608c7511b752.png)

**Comment by deckerla** [comment] 2022-01-12 20:47
How about try:

    Fetch(t,'sigsbee',server='https://www.reproducibility.org’)

In the SConstruct folder?  
It seems like your $RSF_DATASERVER variable may be set to “http://www.ahay.org <http://www.ahay.org/>”, so if the proposed change works you may want to check the value of that environmental variable.
I believe if it is left blank it defaults to https://www.reproducibility.org <https://www.reproducibility.org/> 

Here’s some info:

https://reproducibility.org/wiki/SCons#Fetch.28.3Cfile.5Bs.5D.3E.2C.3Cdirectory.3E.2C.5Boptions.5D.29 <https://reproducibility.org/wiki/SCons#Fetch.28.3Cfile.5Bs.5D.3E.2C.3Cdirectory.3E.2C.5Boptions.5D.29>

**Comment by acse-wz19** [comment] 2022-01-25 23:28
I have the same problem, and I try the method you provide. It still not work for me. 
![image](https://user-images.githubusercontent.com/56032987/151076974-220da080-68c0-4ed3-aab7-9cd600fb9c60.png)

**Comment by acse-wz19** [comment] 2022-01-25 23:32
![image](https://user-images.githubusercontent.com/56032987/151077255-3fcb98d3-d5b7-412b-b93f-7a1e1c4e4a89.png)

**Comment by acse-wz19** [comment] 2022-01-25 23:57
When I click the data in the website, the data is open rather than download.
![image](https://user-images.githubusercontent.com/56032987/151079665-fdf65af0-ecfa-4451-9303-0b3e5055ad7d.png)

**Closed** 2022-02-22 19:04 UTC
Labels: enhancement

**Comment by ale00999-lab** [comment] 2022-02-22 19:05
I had a problem in the installation, and the model is already working correctly for me, thanks for your help.
