### ISSUE TITLE
How to make OpenMP works with Madagascar on Mac os ？

### ISSUE THREAD

**Issue by Robinzzs** [ahay/src#149] opened 2019-01-28 04:44 UTC
My Mac os version is Sierra 10.12.6, and I use Homebrew as package manager to download software packages. 
After  ./configure CC=clang CXX=clang++  --prefix=/PATH_INSTALLED
It shows that
checking for OpenMP ... no
I need omp for parallel computation, how can omp works on Mac OS with clang?
Or how can I configure gcc as the C/C++ compiler and work with Madagascar ?

**Comment by zhichenggeng** [comment] 2019-01-28 14:54
This problem is more like about compiler on Mac OS not about Madagascar.
Hope the following links help. I haven't tried it on my Mac.
https://stackoverflow.com/questions/35134681/installing-openmp-on-mac-os-x-10-11
http://blog.llvm.org/2015/05/openmp-support_22.html

**Comment by ediaz** [comment] 2019-01-28 22:20
As @zhichenggeng said, this issue is not related to Madagascar

**Comment by Robinzzs** [comment] 2019-01-29 02:19
@zhichenggeng  Thank you for reply me.
First of all, I have already goolge the question about LLVM, Clang and OpenMP .
Also I fixed these problem as 
Install libomp and llvm （clang-omp can not be find in Hombrew），
#LLVM OpenMP
export PATH="/usr/local/opt/llvm/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/llvm/lib"
export CPPFLAGS="-I/usr/local/opt/llvm/include"
have been write in my ./zshrc,

and Clang can run with omp well on my Mac. 
I write a program omp.c to test 
#include <stdio.h>
#include <omp.h>
#define COUNT 5
int main(int argc, char* argv[])
{
  int i;
  omp_set_num_threads(4);
#pragma omp parallel for
    for(i=0; i < COUNT;i++) {
      printf("thread=%d, i=%d\n", omp_get_thread_num(), i);
    }
  return 0;
}

compiling as command 
clang -fopenmp omp.c -o omp

the ouput shows as 
➜  ./omp
thread=3, i=4
thread=0, i=0
thread=2, i=3
thread=1, i=2
thread=0, i=1

So finally I wonder that ./configure can not find OpenMP while configure the environment
for Madagascar. Now I suspect that  framework/configure.py did not find the omp library in
right place.

**Comment by zhichenggeng** [comment] 2019-02-04 22:59
@Robinzzs Sorry, I just saw your comment.
Could you first check the log file for configuring Madagascar. The file name is `config.log`.
In that file, searching `-fopenmp`, you should find lines similar to the below:
```
gcc -o .sconf_temp/conftest_24.o -c -O2 -x c -std=gnu99 -Wall -pedantic -fopenmp -I/opt/local/include .sconf_temp/conftest_24.c
clang: error: unsupported option '-fopenmp'
scons: Configure: no
```
The first line is the command that Madagascar uses to check if you have openmp. 
Hope this could help you. 
You can also provide me the command in your log file so that I can help you.

**Comment by yunzhishi** [comment] 2019-02-05 01:56
@Robinzzs I noticed that you may be not using the OpenMP-enabled version of clang/clang++ path for Madagascar setup:

> After ./configure CC=clang CXX=clang++ --prefix=/PATH_INSTALLED

The usage above actually links the scons compiler to the Apple native clang in `/usr/bin/`; however, the OpenMP-enabled version of clang is installed via Homebrew in `/usr/local/opt/llvm/bin/`. You can double check by running the commands: `which clang` and `which clang++`.

I suggest you try setup the Madagascar configuration this way:
```shell
./configure CC=`which clang` CXX=`which clang++` --prefix=/PATH_INSTALLED
```
and see if OpenMP could be correctly linked.

**Comment by Robinzzs** [comment] 2019-02-22 16:43
Sorry for reply so late, busy Spring Festival : )
It's wired that  scons complier links the version of clang. I  already config LLVM version clang as  default complier : 
```shell
➜  which clang
/usr/local/opt/llvm/bin/clang
➜  clang --version
clang version 7.0.1 (tags/RELEASE_701/final)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
```
It still use Apple native clang . While I use 
``` shell
./configure CC=clang CXX=clang++ --prefix=/PATH_INSTALLED
```
that the command in `config.log` file display as:
```
scons: Configure: checking for OpenMP ... 
.sconf_temp/conftest_23.c <-
  |
  |    #include <omp.h>
  |    int main(void) {
  |    int nt;
  |#pragma omp parallel
  |{
  |    nt = omp_get_num_threads();
  |}
  |    return 0;
  |    }
  |    
clang -o .sconf_temp/conftest_23.o -c -O2 -fopenmp -I/opt/local/include .sconf_temp/conftest_23.c
clang: error: unsupported option '-fopenmp'
scons: Configure: no
```
And I changed the configuration as:
```shell
./configure CC=`which clang` CXX=`which clang++` --prefix=/PATH_INSTALLED
```
The OpenMP can be found:
```
checking for OpenMP ... yes
```
and `config.log` file shows:
```
scons: Configure: checking for OpenMP ... 
.sconf_temp/conftest_25.c <-
  |
  |    #include <omp.h>
  |    int main(void) {
  |    int nt;
  |#pragma omp parallel
  |{
  |    nt = omp_get_num_threads();
  |}
  |    return 0;
  |    }
  |    
/usr/local/opt/llvm/bin/clang -o .sconf_temp/conftest_25.o -c -O2 -fopenmp -I/opt/local/include .sconf_temp/conftest_25.c
/usr/local/opt/llvm/bin/clang -o .sconf_temp/sfconftest_25 -framework Accelerate -fopenmp .sconf_temp/conftest_25.o -L/opt/local/lib -lm -lmx
ld: warning: directory not found for option '-L/opt/local/lib'
scons: Configure: yes
```
Then I started install Madagascar as `scons install`. There are some little problems during the installation：
1. It may encounter errors with MPI，and as I reinstalled open-mpi，the  problem disappeared.
2.It may display error while compile .f90 file, and I add `API=f90` in configure command.
After finishing the installation, OpenMp works well, except the warning always display:
```
ld: warning: directory not found for option '-L/opt/local/lib'
``` 
It seems that LDFLAGS can not find the directory of packages' library install by Homebrew in /usr/local/lib.

**Comment by zhichenggeng** [comment] 2019-02-22 18:55
You don't need to worry about this warning.     
```
# Mac OS X include path, library path, and link flags
    if plat['OS'] == 'darwin':
        context.env['LINKFLAGS'] = context.env.get('LINKFLAGS','') + \
            ' -framework Accelerate '
#        context.env['CPPDEFINES'] = path_get(context,'CPPDEFINES',
#                                            '__ACCELERATE__')
        if os.path.isdir('/opt'):   # paths for MacPorts
            context.env['CPPPATH'] = path_get(context,'CPPPATH',
                                              '/opt/local/include')
            context.env['LIBPATH'] = path_get(context,'LIBPATH',
                                              '/opt/local/lib')
```
The warning is caused by the code above, which is located in `framework/configure.py`.
It basically adds all possible paths of library to `LIBPATH`. You might have `/opt` directory, but don't have `/opt/local/lib`

**Comment by zhichenggeng** [comment] 2019-02-22 18:57
Should be fixed in 7bc72675c05fe532a7239c93c65db1433f91fdfd. Because I couldn't reproduce the warning, I'm not sure if it works. @Robinzzs If it still shows the warning, please let me know.

**Comment by Robinzzs** [comment] 2019-02-23 04:08
👍After upgrade, the warning do not shows again. 
By the way, there really have some errors with MPI while I reinstall Madagascar：
```
/usr/local/bin/mpicc -o build/user/cwp/Mbigmpiencode.o -c -O2 -fopenmp -Ibuild/include -Ibuild/include build/user/cwp/Mbigmpiencode.c
clang: error: unsupported option '-fopenmp'
scons: *** [build/user/cwp/Mbigmpiencode.o] Error 1
scons: building terminated because of errors.
```
as I remove `open-mpi`, the error do not shows.

**Comment by zhichenggeng** [comment] 2019-02-25 16:20
@Robinzzs What do you mean by 'remove open-mpi'? Uninstall it?

**Comment by Robinzzs** [comment] 2019-03-01 05:54
Yes, uninstall MPI by `brew remove open-mpi`.
while compile `/user/cwp/Mbigmpiencode.c` file, it seems to use 'mpicc' to compile, and shows the error 
`unsupported option '-fopenmp'` .

**Comment by zhichenggeng** [comment] 2019-03-03 21:46
@Robinzzs I finally found a way to solve this problem. This method is kind of complicated, but at least it works.
First of all, you need to install open-mpi with clang:
```
brew install open-mpi --cc=clang
```
You have already set the environment so that `mpicc` uses `clang` from llvm to compile and `-fopenmp` is supported in `mpicc`. You can write a simple program to test it.

However, it's kind of weird that the same error happens during installation. From the error message, it looks like `mpicc` uses default `clang` to compile.I don't know what causes this problem. 

But one way to fix it is that you can edit file  `/usr/local/Cellar/open-mpi/4.0.0/share/openmpi/mpicc-wrapper-data.txt` to specify the absolute path of `clang` for `mpicc`. In this file, you only need change `compiler=clang` to the absolute path of `clang`.
For me, it should be`compiler=/usr/local/opt/llvm/bin/clang`. You also need to change the one for `mpicxx`, correspondingly.

**Comment by Robinzzs** [comment] 2019-03-06 02:55
@zhichenggeng 
Follow your steps，the error caused by open-mpi can be figure out.
And I found that install open-mpi like this way can simplify these steps:
```shell
brew install open-mpi --cc=llvm_clang
``` 
It depend on the info form `brew help install`:
```
     --cc                         Attempt to compile using provided
                                     compiler. compiler should be the name
                                     of the compiler's executable, for instance
                                     gcc-7 for GCC 7. In order to use LLVM's
                                     clang, use llvm_clang. To specify the
                                     Apple-provided clang, use clang. This
                                     parameter will only accept compilers that
                                     are provided by Homebrew or bundled with
                                     macOS. Please do not file issues if you
                                     encounter errors while using this flag.
```

**Comment by zhichenggeng** [comment] 2019-03-06 14:39
@Robinzzs Yeah. I tried to use `--cc=llvm_clang`, but it always says `llvm_clang` can't be found. I don't know why. Then I tried to change the wrapper file. Anyway, it works.

**Closed by zhichenggeng** 2019-03-06 14:39 UTC

**Comment by acse-wz19** [comment] 2021-10-02 07:40
I have the same problem, but when I use brew remove open-mpi , after configure mpi still exist,  I don't know why , and after google I can not solve this problem
